name: CraftDreams
author: Felxq
main: de.Felxq.Main.Main
version: 1.0
api-version: 1.13

commands:
   spawn:
   setspawn:
   setshop:
   money:
   team:
   pay:
   gm:
   home:
   sethome:
   heal:
   fly:
   day:
   clear:
   cc:
   clearchat:
   ci:
   bc:
   broadcast:
   invsee:
   msg:
   spy:
   vanish:
   tp:
   tpaccept:
   tpa:
   job:
   beruf:
   tpdeny:
   echo:
   setJobLevel:
   check:
   weblogin: